### ISSUE TITLE
[加入新群] 

### ISSUE THREAD

**Issue by aimste** [Moonlark-Dev/XDbot2#689]
### 开始之前……

- [X] 我是群组的管理员，或群主或管理员允许机器人入群

### QQ号

2778741821

### QQ群

1037072643

### 入群方式

本群无特殊入群答案，支持搜索群号加群，无需二维码或入群链接。

### 群主或管理员同意

我是本群的群主或管理员。

**Comment by This-is-XiaoDeng** [comment]
![图片](https://github.com/Moonlark-Dev/XDbot2/assets/104149371/7571fe31-1445-416b-b712-32447b6f20ea)

XDbot2 （节点: `0x01`, QQ: `3457603681`）已向此群发送加群申请，请留意群通知
