### ISSUE TITLE
[Bug 反馈] 回声洞判断相似问题

### ISSUE THREAD

**Issue by HOStudio123** [Moonlark-Dev/XDbot2#693]
### 描述

![Image_1721178727558](https://github.com/user-attachments/assets/ac42a020-319d-4b8b-ae97-c80181c0b7e5)
直接看图图片吧

### 重现步骤

你再投稿一下我的图片

### 截图
在上面

**Comment by This-is-XiaoDeng** [comment]
你发错地方了……

**Comment by This-is-XiaoDeng** [comment]
你应该将此 Issue 发送到 Moonlark-Dev/Moonlark

**Comment by HOStudio123** [comment]
@This-is-XiaoDeng 应该发哪()

**Comment by HOStudio123** [comment]
ok
